"""SPICE netlist (.cir) generator."""

from __future__ import annotations

from netlist_converter.generators.base import NetlistGenerator
from netlist_converter.models import Component, ComponentType, Netlist

SPICE_PREFIX_MAP: dict[ComponentType, str] = {
    ComponentType.RESISTOR: "R",
    ComponentType.CAPACITOR: "C",
    ComponentType.INDUCTOR: "L",
    ComponentType.DIODE: "D",
    ComponentType.TRANSISTOR: "Q",
    ComponentType.VOLTAGE_REGULATOR: "X",
    ComponentType.OPAMP: "X",
    ComponentType.IC: "X",
    ComponentType.LED: "D",
    ComponentType.CRYSTAL: "X",
    ComponentType.FUSE: "R",
    ComponentType.RELAY: "X",
    ComponentType.TRANSFORMER: "X",
    ComponentType.SWITCH: "S",
    ComponentType.CONNECTOR: "X",
    ComponentType.OTHER: "X",
}


def _build_node_map(netlist: Netlist) -> dict[tuple[str, str], str]:
    """Map (component_ref, pin) -> net_name for quick lookup."""
    node_map: dict[tuple[str, str], str] = {}
    for net in netlist.nets:
        for pin_ref in net.pins:
            node_map[(pin_ref.component_ref, pin_ref.pin)] = net.name
    return node_map


def _component_to_spice(comp: Component, node_map: dict[tuple[str, str], str]) -> str:
    """Render a single component as a SPICE netlist line."""
    nodes = []
    for pin in comp.pins:
        net_name = node_map.get((comp.reference, pin.number), "0")
        nodes.append(net_name)

    if not nodes:
        nodes = ["0", "0"]

    prefix = SPICE_PREFIX_MAP.get(comp.component_type, "X")
    ref = comp.reference
    if not ref.upper().startswith(prefix):
        ref = f"{prefix}{ref}"

    value = comp.value if comp.value else comp.reference
    node_str = " ".join(nodes)
    return f"{ref} {node_str} {value}"


class SpiceGenerator(NetlistGenerator):
    """Generate SPICE-compatible .cir netlist files."""

    @property
    def file_extension(self) -> str:
        return ".cir"

    def generate(self, netlist: Netlist) -> str:
        lines: list[str] = []

        title = f"* Netlist: {netlist.metadata.source_file}"
        lines.append(title)
        lines.append(f"* Generated by netlist-converter v{netlist.metadata.tool_version}")
        lines.append(f"* Confidence: {netlist.metadata.confidence:.2f}")
        lines.append("")

        node_map = _build_node_map(netlist)

        for comp in netlist.components:
            lines.append(_component_to_spice(comp, node_map))

        lines.append("")
        lines.append(".end")
        lines.append("")

        return "\n".join(lines)
